+p_xml: 'version="1.0" encoding="UTF-8" standalone="yes" '
+directive: DOCTYPE bugzilla SYSTEM "http://bugzilla.fieldtriptoolbox.org/page.cgi?id=bugzilla.dtd"
bugzilla:
  +@version: 4.4.1
  +@urlbase: http://bugzilla.fieldtriptoolbox.org/
  +@maintainer: r.oostenveld@donders.ru.nl
  bug:
    bug_id: "2103"
    creation_ts: 2013-04-11 13:36:00 +0200
    short_desc: 'ft_freqstatistics: when input is rpt_chan_freq_time cfg.avgovertime = ''yes'' gives error while monte-carlo+cluster'
    delta_ts: 2013-06-05 11:00:17 +0200
    reporter_accessible: "1"
    cclist_accessible: "1"
    classification_id: "1"
    classification: Unclassified
    product: FieldTrip
    component: core
    version: unspecified
    rep_platform: PC
    op_sys: Windows
    bug_status: CLOSED
    resolution: WORKSFORME
    bug_file_loc:
    status_whiteboard:
    keywords:
    priority: P3
    bug_severity: normal
    target_milestone: '---'
    everconfirmed: "1"
    reporter:
      +content: roemer.van.der.meij
      +@name: Roemer van der Meij
    assigned_to: fieldtriptoolbox
    cc:
      - eelke.spaak
      - j.schoffelen
    comment_sort_order: oldest_to_newest
    long_desc:
      - +@isprivate: "0"
        commentid: "10049"
        comment_count: "0"
        who:
          +content: roemer.van.der.meij
          +@name: Roemer van der Meij
        bug_when: 2013-04-11 13:36:05 +0200
        thetext: Error probable caused by the time dimension becoming singleton, which is automatically removed as it's the last one, changing the dimensionality of the data. Error could also be caused by combining cfg.avgovertime = 'yes' with cfg.avgoverfreq = 'yes'
      - +@isprivate: "0"
        commentid: "10050"
        comment_count: "1"
        who:
          +content: eelke.spaak
          +@name: Eelke Spaak
        bug_when: 2013-04-11 13:38:34 +0200
        thetext: Is this a crash? In that case, bug 2022 seems relevant.
      - +@isprivate: "0"
        commentid: "10056"
        comment_count: "2"
        who:
          +content: roemer.van.der.meij
          +@name: Roemer van der Meij
        bug_when: 2013-04-11 15:12:33 +0200
        thetext: "Nope, just an error. Found during the toolkit, so made a very quick report. \nThe error was:\nerror('could not determine the parametric critical value for clustering')"
      - +@isprivate: "0"
        commentid: "10349"
        comment_count: "3"
        who:
          +content: j.schoffelen
          +@name: Jan-Mathijs Schoffelen
        bug_when: 2013-05-01 13:36:52 +0200
        thetext: This has now become a bit cryptic. Can we get some code that reproduces the error? If not, I suggest to wontfix this.
      - +@isprivate: "0"
        commentid: "10613"
        comment_count: "4"
        who:
          +content: roemer.van.der.meij
          +@name: Roemer van der Meij
        bug_when: 2013-06-05 11:00:12 +0200
        thetext: I can't replicate the error either, probably something else was wrong with their data. Setting to worksforme and closing.
