+p_xml: 'version="1.0" encoding="UTF-8" standalone="yes" '
+directive: DOCTYPE bugzilla SYSTEM "http://bugzilla.fieldtriptoolbox.org/page.cgi?id=bugzilla.dtd"
bugzilla:
  +@version: 4.4.1
  +@urlbase: http://bugzilla.fieldtriptoolbox.org/
  +@maintainer: r.oostenveld@donders.ru.nl
  bug:
    bug_id: "2689"
    creation_ts: 2014-09-18 15:03:00 +0200
    short_desc: ft_datatype returns error because function 'fieldnames' is not recognized
    delta_ts: 2015-02-11 10:40:11 +0100
    reporter_accessible: "1"
    cclist_accessible: "1"
    classification_id: "1"
    classification: Unclassified
    product: FieldTrip
    component: core
    version: unspecified
    rep_platform: Other
    op_sys: Linux
    bug_status: CLOSED
    resolution: INVALID
    bug_file_loc:
    status_whiteboard:
    keywords:
    priority: P5
    bug_severity: normal
    target_milestone: '---'
    everconfirmed: "1"
    reporter:
      +content: s.vanpelt
      +@name: Stan van Pelt
    assigned_to:
      +content: r.oostenveld
      +@name: Robert Oostenveld
    cc: r.oostenveld
    comment_sort_order: oldest_to_newest
    long_desc:
      - +@isprivate: "0"
        commentid: "14376"
        comment_count: "0"
        who:
          +content: s.vanpelt
          +@name: Stan van Pelt
        bug_when: 2014-09-18 15:03:43 +0200
        thetext: |-
          When running ft_prepare_leadfield, this function subsequently calls the subroutines ft_checkdata, ft_datatype, and its subroutine check_chan. This last subroutine gives an error that it does not recognize 'fieldnames' as a function (line 159), although this is a built-in matlab-routine.
          I am running the latest FieldTrip version (the one om home/common/fieldtrip).
      - +@isprivate: "0"
        commentid: "14380"
        comment_count: "1"
        who:
          +content: r.oostenveld
          +@name: Robert Oostenveld
        bug_when: 2014-09-18 15:13:34 +0200
        thetext: "(hoe heb je dat nu weer voor elkaar gekregen...)\n\nfieldnames should indeed be recognised as an normal function:\n\n>> which fieldnames.m\n/Applications/MATLAB_R2014a.app/toolbox/matlab/datatypes/fieldnames.m\n\n>> fieldnames(1)\nUndefined function 'fieldnames' for input arguments of type 'double'.\n \n>> fieldnames([])\nUndefined function 'fieldnames' for input arguments of type 'double'.\n \n>> fieldnames('a')\nUndefined function 'fieldnames' for input arguments of type 'char'.\n\nI cannot reproduce the error. \n\nCould you do \"dbstop on error\" and check the input that you are giving to the field names function? And do \"which fieldnames\"?"
      - +@isprivate: "0"
        commentid: "14381"
        comment_count: "2"
        who:
          +content: r.oostenveld
          +@name: Robert Oostenveld
        bug_when: 2014-09-18 15:14:14 +0200
        thetext: |-
          might there something in general be going wrong on the cluster?

          I cannot easily check, as I am in Bham.
      - +@isprivate: "0"
        commentid: "14382"
        comment_count: "3"
        who:
          +content: s.vanpelt
          +@name: Stan van Pelt
        bug_when: 2014-09-18 15:24:31 +0200
        thetext: |-
          Yes, strange indeed. "Which fieldnames" does recognize it. I am looking further into this at the moment, trying to replicate the error with other fucntions/platforms. Cluster seems to work fine..
          Enjoy Birmingham!
      - +@isprivate: "0"
        commentid: "14398"
        comment_count: "4"
        who:
          +content: s.vanpelt
          +@name: Stan van Pelt
        bug_when: 2014-09-22 10:52:18 +0200
        thetext: The error was due to putting an empty matrix as input for ft_prepare_leadfield. Ergo, ft_prepare_leadfield(cfg,[]) gives the error as reported (might have worked in previous FT versions?), ft_prepare_leadfield(cfg) works fine.
      - +@isprivate: "0"
        commentid: "15223"
        comment_count: "5"
        who:
          +content: r.oostenveld
          +@name: Robert Oostenveld
        bug_when: 2015-02-11 10:40:11 +0100
        thetext: Closed several bugs that were recently resolved. Please reopen if you are not happy with the resolution.
