+p_xml: 'version="1.0" encoding="UTF-8" standalone="yes" '
+directive: DOCTYPE bugzilla SYSTEM "http://bugzilla.fieldtriptoolbox.org/page.cgi?id=bugzilla.dtd"
bugzilla:
  +@version: 4.4.1
  +@urlbase: http://bugzilla.fieldtriptoolbox.org/
  +@maintainer: r.oostenveld@donders.ru.nl
  bug:
    bug_id: "2853"
    creation_ts: 2015-02-23 15:29:00 +0100
    short_desc: 'test_ft_sourcenalysis: try-catch statement prevents proper catching of assertion failures'
    delta_ts: 2015-09-15 16:07:00 +0200
    reporter_accessible: "1"
    cclist_accessible: "1"
    classification_id: "1"
    classification: Unclassified
    product: FieldTrip
    component: test
    version: unspecified
    rep_platform: PC
    op_sys: Windows
    bug_status: CLOSED
    resolution: FIXED
    see_also: http://bugzilla.fcdonders.nl/show_bug.cgi?id=2387
    bug_file_loc:
    status_whiteboard:
    keywords:
    priority: P5
    bug_severity: normal
    target_milestone: '---'
    everconfirmed: "1"
    reporter:
      +content: j.schoffelen
      +@name: Jan-Mathijs Schoffelen
    assigned_to:
      +content: j.schoffelen
      +@name: Jan-Mathijs Schoffelen
    cc: r.oostenveld
    comment_sort_order: oldest_to_newest
    long_desc:
      - +@isprivate: "0"
        commentid: "15432"
        comment_count: "0"
        who:
          +content: j.schoffelen
          +@name: Jan-Mathijs Schoffelen
        bug_when: 2015-02-23 15:29:33 +0100
        thetext: this is occurring around line 1030-1055
      - +@isprivate: "0"
        commentid: "15433"
        comment_count: "1"
        who:
          +content: j.schoffelen
          +@name: Jan-Mathijs Schoffelen
        bug_when: 2015-02-23 15:31:29 +0100
        thetext: |-
          datainfo=ref_datasets;
          ft_test_sourceanalysis(datainfo(9));

          The above would in my expection yield massive problems, due to the recent change in handling of the inside field, because it would be comparing the current output against the output stored on disk, with the insides still indexed.
      - +@isprivate: "0"
        commentid: "15434"
        comment_count: "2"
        who:
          +content: j.schoffelen
          +@name: Jan-Mathijs Schoffelen
        bug_when: 2015-02-23 15:32:51 +0100
        thetext: I'm taking it for now to look into the issue. I may reassign when the test script starts crashing. Once it starts crashing we need to compare the new output against the old outputs, and ascertain that the only cause of the assertion failure is due to the new inside handling. If so, we need to re-create the benchmark data.
      - +@isprivate: "0"
        commentid: "15435"
        comment_count: "3"
        who:
          +content: j.schoffelen
          +@name: Jan-Mathijs Schoffelen
        bug_when: 2015-02-23 15:42:38 +0100
        thetext: |-
          [jansch@mentat002 fieldtrip]$ svn log test/test_ft_sourceanalysis.m
          ------------------------------------------------------------------------
          r10249 | jansch | 2015-02-23 15:41:24 +0100 (Mon, 23 Feb 2015) | 1 line

          enhancement - properly error when assertion fails
          ------------------------------------------------------------------------
      - +@isprivate: "0"
        commentid: "15518"
        comment_count: "4"
        who:
          +content: j.schoffelen
          +@name: Jan-Mathijs Schoffelen
        bug_when: 2015-03-11 09:37:27 +0100
        thetext: "I will test (non-exhaustively) whether the failed assertions are due to the new representation of the inside only + some numeric round off issues in the numeric data. \nIf so, I will replace the current 'latest' data with a fresh version.\n\n@Robert: do I need to back up the previous version?"
      - +@isprivate: "0"
        commentid: "15519"
        comment_count: "5"
        who:
          +content: r.oostenveld
          +@name: Robert Oostenveld
        bug_when: 2015-03-11 11:23:54 +0100
        thetext: |-
          (In reply to Jan-Mathijs Schoffelen from comment #4)

          no, I don't consider it needed to back up this.
      - +@isprivate: "0"
        commentid: "15542"
        comment_count: "6"
        who:
          +content: j.schoffelen
          +@name: Jan-Mathijs Schoffelen
        bug_when: 2015-03-17 09:10:08 +0100
        thetext: |-
          apart from the test function failing due to changes in the source structure, there are a bunch of issues which causes specific examples not to be computed due to a crash in ft_sourceanalysis, or one of its depfuns.

          1. due to bug 2387, when the geometric units of the input arguments are incompatible. -> I suggest to circumvent this by temporarily equating the units explicitly in test_ft_sourceanalysis with ft_convert_units
          2. missing field 'latency'
          3. missing field 'frequency'
          4. ... other not yet identified.

          I'll look into 2 and 3

          Also, there are some warnings issued due to old style cfg settings: cfg.keepfilter should be cfg.dics.keepfilter etc., causing problems with pedantic checkconfig'ing.
      - +@isprivate: "0"
        commentid: "15543"
        comment_count: "7"
        who:
          +content: j.schoffelen
          +@name: Jan-Mathijs Schoffelen
        bug_when: 2015-03-17 09:16:03 +0100
        thetext: |-
          addition to my previous comment, point 1.
          The case I am looking into now erroneously sets the units of the grid (with 100 positions expressed in cm) to dm. So this particular case seems to go wrong somewhere else, and is solvable by explicitly stating the units.
      - +@isprivate: "0"
        commentid: "15544"
        comment_count: "8"
        who:
          +content: j.schoffelen
          +@name: Jan-Mathijs Schoffelen
        bug_when: 2015-03-17 09:22:43 +0100
        thetext: stating the units for the cortical sheets fixes issue 1.
      - +@isprivate: "0"
        commentid: "15545"
        comment_count: "9"
        who:
          +content: r.oostenveld
          +@name: Robert Oostenveld
        bug_when: 2015-03-17 10:05:43 +0100
        thetext: "(In reply to Jan-Mathijs Schoffelen from comment #6)\n\n> Also, there are some warnings issued due to old style cfg \n> settings: cfg.keepfilter should be cfg.dics.keepfilter etc., \n> causing problems with pedantic checkconfig'ing.\n\nI sometimes do an explicit \n  global ft_default\n  ft_default = [];\nat the start of a test script to ensure that my personal (pedantic) default does not apply, but rather the default (loose)."
      - +@isprivate: "0"
        commentid: "15586"
        comment_count: "10"
        who:
          +content: j.schoffelen
          +@name: Jan-Mathijs Schoffelen
        bug_when: 2015-04-03 09:14:17 +0200
        thetext: "[jansch@mentat002 test]$ svn commit -m \"enhancement - improved test function and re-computed benchmark results\" test_ft_sourceanalysis.m test_ft_sourceanalysis_combinations_allowed.m test_ft_sourceanalysis_combinations_forbidden.m ../ft_sourceanalysis.m \nSending        ft_sourceanalysis.m\nSending        test/test_ft_sourceanalysis.m\nAdding         test/test_ft_sourceanalysis_combinations_allowed.m\nAdding         test/test_ft_sourceanalysis_combinations_forbidden.m\nTransmitting file data ....\nCommitted revision 10316."
      - +@isprivate: "0"
        commentid: "15587"
        comment_count: "11"
        who:
          +content: j.schoffelen
          +@name: Jan-Mathijs Schoffelen
        bug_when: 2015-04-03 09:15:37 +0200
        thetext: |-
          the test function should run through again.

          To be done: I made a distinction between allowed and forbidden combinations (e.g. doing DICS on timelock data). There exists benchmark data like this, but I suggest that we explicitly throw an error in ft_sourceanalysis when a user wants something like this (I have no idea what's in the benchmark data) and to remove the test data of these combinations.
      - +@isprivate: "0"
        commentid: "16107"
        comment_count: "12"
        who:
          +content: j.schoffelen
          +@name: Jan-Mathijs Schoffelen
        bug_when: 2015-09-15 16:05:46 +0200
        thetext: Test function seems to be kind of working now, closing.
      - +@isprivate: "0"
        commentid: "16108"
        comment_count: "13"
        who:
          +content: j.schoffelen
          +@name: Jan-Mathijs Schoffelen
        bug_when: 2015-09-15 16:07:00 +0200
        thetext: Well, actually I am not sure whether the test function actually works, but at least the try catch issue is resolved, so true to its title, this bug has been addressed
