+p_xml: 'version="1.0" encoding="UTF-8" standalone="yes" '
+directive: DOCTYPE bugzilla SYSTEM "http://bugzilla.fieldtriptoolbox.org/page.cgi?id=bugzilla.dtd"
bugzilla:
  +@version: 4.4.1
  +@urlbase: http://bugzilla.fieldtriptoolbox.org/
  +@maintainer: r.oostenveld@donders.ru.nl
  bug:
    bug_id: "3041"
    creation_ts: 2016-01-12 21:02:00 +0100
    short_desc: Error in find_innermost_boundary (line 44)
    delta_ts: 2016-05-05 20:32:02 +0200
    reporter_accessible: "1"
    cclist_accessible: "1"
    classification_id: "1"
    classification: Unclassified
    product: FieldTrip
    component: forward
    version: unspecified
    rep_platform: PC
    op_sys: Windows
    bug_status: CLOSED
    resolution: FIXED
    bug_file_loc:
    status_whiteboard:
    keywords:
    priority: P5
    bug_severity: normal
    target_milestone: '---'
    everconfirmed: "1"
    reporter:
      +content: thomasmas
      +@name: Thomas Mastropasqua
    assigned_to:
      +content: j.schoffelen
      +@name: Jan-Mathijs Schoffelen
    cc: j.schoffelen
    comment_sort_order: oldest_to_newest
    long_desc:
      - +@isprivate: "0"
        commentid: "16603"
        comment_count: "0"
        attachid: "766"
        who:
          +content: thomasmas
          +@name: Thomas Mastropasqua
        bug_when: 2016-01-12 21:02:10 +0100
        thetext: "Created attachment 766\nFigure showing the error message\n\nDear Fieldtrip developers, \n\nI've just downloaded the latest version of Fieldtrip-lite (20160111) in order to use it as an EEGLAB extension. \n\nI would like to remove dipoles that are fitted outside the brain volume and when I try to do that, I get an error in the function find_innermost_boundary, which is generated by a reference to non-existent field 'pos' (for more details, see figure Error.png in attachment).\n\nI read on the Fieldtrip site that the present error has already been fixed and I'm wondering what I'm doing wrong.\n\nThank you for your help.\n\nAll the best,\nThomas"
      - +@isprivate: "0"
        commentid: "16927"
        comment_count: "1"
        who:
          +content: j.schoffelen
          +@name: Jan-Mathijs Schoffelen
        bug_when: 2016-02-22 13:53:12 +0100
        thetext: |-
          This is probably caused by your input variable 'headmodel' being old-fashioned, i.e. containing position information in a 'pnt' field, rather than a 'pos' field.

          The solution would be to ensure the up-to-date data representation with a call to ft_datatype_headmodel as the first code line in ft_sourcedepth.

          I don't know where the 'vol' variable was obtained, but if this one came shipped with eeglab (or is generated within eeglab) it may be useful to notify the developers of eeglab that the 'pnt' may need to be changed into 'pos'.

          On the fieldtrip end, I will update the templates stored in fieldtrip/template/headmodel.
      - +@isprivate: "0"
        commentid: "16929"
        comment_count: "2"
        who:
          +content: j.schoffelen
          +@name: Jan-Mathijs Schoffelen
        bug_when: 2016-02-22 13:59:54 +0100
        thetext: |-
          I have updated ft_sourcedepth (as well as the template headmodels) in the current version of fieldtrip on github

          github.com/fieldtrip/fieldtrip
      - +@isprivate: "0"
        commentid: "17044"
        comment_count: "3"
        attachid: "781"
        who:
          +content: thomasmas
          +@name: Thomas Mastropasqua
        bug_when: 2016-03-02 15:42:02 +0100
        thetext: |-
          Created attachment 781
          Figure showing the new error message
      - +@isprivate: "0"
        commentid: "17045"
        comment_count: "4"
        who:
          +content: thomasmas
          +@name: Thomas Mastropasqua
        bug_when: 2016-03-02 15:44:03 +0100
        thetext: "Dear Jan-Mathijs,\n\nThank you for your reply.\nUnfortunately, the changes you made did not fix the problem. Now I'm getting a new error message (see below and the image in attachment).\nThe EEGLAB developers told me that they are aware of the problem but they cannot solve it.\n\nJust to let you know.\n\nAll the best,\nThomas\n\n\n\nIndex exceeds matrix dimensions.\n\nError in ft_sourcedepth (line 79)\n      [proj, dist(j)] = ptriproj(v1, v2, v3, dippos(i,:), 1);\n\nError in eeg_dipselect (line 78)\n    depth = ft_sourcedepth(posxyz, vol);\n\nError in std_editset (line 234)\n                            indleft = eeg_dipselect(ALLEEG(idat), rv*100,'inbrain');\n\nError in pop_study (line 405)\n                STUDY = std_editset(STUDY, ALLEEG, 'commands', { 'inbrain', 'on', 'dipselect' str2num(res{1})/100 'return' });\n \nError using inputgui (line 204)\nError while evaluating UIControl Callback"
      - +@isprivate: "0"
        commentid: "17046"
        comment_count: "5"
        who:
          +content: j.schoffelen
          +@name: Jan-Mathijs Schoffelen
        bug_when: 2016-03-02 16:02:40 +0100
        thetext: |-
          npos should be size(dippos,1) rather than size(pos,1)

          I guess that you already saw that.

          It's fixed now.
    attachment:
      - +@isobsolete: "0"
        +@ispatch: "0"
        +@isprivate: "0"
        attachid: "766"
        date: 2016-01-12 21:02:00 +0100
        delta_ts: 2016-01-12 21:02:10 +0100
        desc: Figure showing the error message
        filename: Error.png
        type: image/png
        size: "217376"
        attacher:
          +content: thomasmas
          +@name: Thomas Mastropasqua
        data: REMOVED
      - +@isobsolete: "0"
        +@ispatch: "0"
        +@isprivate: "0"
        attachid: "781"
        date: 2016-03-02 15:42:00 +0100
        delta_ts: 2016-03-02 15:42:02 +0100
        desc: Figure showing the new error message
        filename: NewError.jpg
        type: image/jpeg
        size: "615033"
        attacher:
          +content: thomasmas
          +@name: Thomas Mastropasqua
        data: REMOVED
