+p_xml: 'version="1.0" encoding="UTF-8" standalone="yes" '
+directive: DOCTYPE bugzilla SYSTEM "http://bugzilla.fieldtriptoolbox.org/page.cgi?id=bugzilla.dtd"
bugzilla:
  +@version: 4.4.1
  +@urlbase: http://bugzilla.fieldtriptoolbox.org/
  +@maintainer: r.oostenveld@donders.ru.nl
  bug:
    bug_id: "3289"
    creation_ts: 2017-04-25 10:44:00 +0200
    short_desc: write mesh vista with anisotropy conductivity tensor on windows
    delta_ts: 2017-04-25 10:48:04 +0200
    reporter_accessible: "1"
    cclist_accessible: "1"
    classification_id: "1"
    classification: Unclassified
    product: FieldTrip
    component: external
    version: unspecified
    rep_platform: PC
    op_sys: Windows
    bug_status: NEW
    resolution:
    bug_file_loc:
    status_whiteboard:
    keywords:
    priority: P5
    bug_severity: normal
    target_milestone: '---'
    everconfirmed: "1"
    reporter:
      +content: antonakakismar
      +@name: Marios Antonakakis
    assigned_to:
      +content: r.oostenveld
      +@name: Robert Oostenveld
    cc:
      - carsten.wolters
      - j.vorwerk
    comment_sort_order: oldest_to_newest
    long_desc:
      - +@isprivate: "0"
        commentid: "18587"
        comment_count: "0"
        who:
          +content: antonakakismar
          +@name: Marios Antonakakis
        bug_when: 2017-04-25 10:44:38 +0200
        thetext: "I am trying to write the created mesh with six tissues with its correspond anisotropy conductivity tensor but I got this error\nAccess violation detected at Tue Apr 25 10:37:50 2017\nand then it need to restart matlab\n\nThis call works well: write_vista_mesh([path_simbio subject_id{subj} '.v'],mesh.pos,mesh.hex,mesh.tissue);\n\nThis call does not work: write_vista_mesh([path_simbio subject_id{subj} '.v'],mesh.pos,mesh.hex,mesh.tissue,condtensor)\n\nin a windows machine.\n\nI attached the mesh \nhttps://www.dropbox.com/s/cefvu5iwye9ghsi/mesh.mat?dl=0\n\nand the correspond conductivity tensor\nhttps://www.dropbox.com/s/y1gj11m0mxo7n04/conductivity_tensor.mat?dl=0"
      - +@isprivate: "0"
        commentid: "18588"
        comment_count: "1"
        who:
          +content: r.oostenveld
          +@name: Robert Oostenveld
        bug_when: 2017-04-25 10:48:04 +0200
        thetext: |-
          this is an error in an external mex file (contained within fieldtrip/external/simbio). I don't have the source code of that mex file, so cannot fix it.

          I have CCed the simbio developers on this bug, perhaps they can help.
