+p_xml: 'version="1.0" encoding="UTF-8" standalone="yes" '
+directive: DOCTYPE bugzilla SYSTEM "http://bugzilla.fieldtriptoolbox.org/page.cgi?id=bugzilla.dtd"
bugzilla:
  +@version: 4.4.1
  +@urlbase: http://bugzilla.fieldtriptoolbox.org/
  +@maintainer: r.oostenveld@donders.ru.nl
  bug:
    bug_id: "3336"
    creation_ts: 2017-08-24 08:45:00 +0200
    short_desc: get rid of confusing stack trace of ft_errror
    delta_ts: 2019-08-10 12:37:17 +0200
    reporter_accessible: "1"
    cclist_accessible: "1"
    classification_id: "1"
    classification: Unclassified
    product: FieldTrip
    component: core
    version: unspecified
    rep_platform: PC
    op_sys: Mac OS
    bug_status: CLOSED
    resolution: FIXED
    bug_file_loc:
    status_whiteboard:
    keywords:
    priority: P5
    bug_severity: normal
    target_milestone: '---'
    everconfirmed: "1"
    reporter:
      +content: r.oostenveld
      +@name: Robert Oostenveld
    assigned_to: fieldtriptoolbox
    cc:
      - dmatthes
      - stephen.whitmarsh
    comment_sort_order: oldest_to_newest
    long_desc:
      - +@isprivate: "0"
        commentid: "18871"
        comment_count: "0"
        who:
          +content: r.oostenveld
          +@name: Robert Oostenveld
        bug_when: 2017-08-24 08:45:23 +0200
        thetext: |-
          The stack trace is important in error messages, and ft_error makes it rather confusing by adding ft_error and ft_notification to the stack. Except for the automatic messageId, there is nothing that makes ft_error better than a normal error.

          For ft_warning the "once" functionality makes it valuable.

          The messageId can be maintained by moving that from ft_notification to a stand-alone function.
      - +@isprivate: "0"
        commentid: "18872"
        comment_count: "1"
        who:
          +content: r.oostenveld
          +@name: Robert Oostenveld
        bug_when: 2017-08-24 09:00:59 +0200
        thetext: '[bug3336-ft_error 043d2ab] implemented defaultId separate from ft_notification, removed ft_error and ft_warning from engine and peer (just like qsub), added ft_warning/ft_notification more consistently to all private directories. See http://bugzilla.fieldtriptoolbox.org/show_bug.cgi?id=3336'
      - +@isprivate: "0"
        commentid: "18875"
        comment_count: "2"
        who:
          +content: r.oostenveld
          +@name: Robert Oostenveld
        bug_when: 2017-08-24 12:46:36 +0200
        thetext: |-
          I merged https://github.com/fieldtrip/fieldtrip/pull/501

          There were some issues with synchronizing defaultId, so I had to do some additional commits later on (which did not go through a PR).

          qsub, peer and engine are now all clean.
      - +@isprivate: "0"
        commentid: "18876"
        comment_count: "3"
        who:
          +content: r.oostenveld
          +@name: Robert Oostenveld
        bug_when: 2017-08-24 13:01:38 +0200
        thetext: |-
          the private/defaultId helper function now seems to work correctly. That means that ft_error(msg) can be replaced by error(defaultId, msg). The following works as expected in both cases

          -------
          function test_error

          subfunction

          function subfunction
          % ft_error('something went wrong');
          error(defaultId, 'something went wrong');
          -------
      - +@isprivate: "0"
        commentid: "18952"
        comment_count: "4"
        who:
          +content: stephen.whitmarsh
          +@name: Stephen Whitmarsh
        bug_when: 2017-09-25 14:01:19 +0200
        thetext: |-
          This might have introduced the error I just reported:

          http://bugzilla.fieldtriptoolbox.org/show_bug.cgi?id=3356
      - +@isprivate: "0"
        commentid: "19607"
        comment_count: "5"
        who:
          +content: r.oostenveld
          +@name: Robert Oostenveld
        bug_when: 2018-11-27 15:28:34 +0100
        thetext: I had a branch bug3335 that included a final commit with a search-and-replace of ft_error(...) into error(defaultId,..). That final commit was stale and would not merge any more. Hence I have just deleted it. I think it should be possible to solve this more elegantly using a trimmed stack. That would not only work for error, but also for warning and (possibly) the other notification levels with a backtrace.
      - +@isprivate: "0"
        commentid: "19608"
        comment_count: "6"
        who:
          +content: r.oostenveld
          +@name: Robert Oostenveld
        bug_when: 2018-11-27 17:08:23 +0100
        thetext: |-
          Just discussed this with JM on the phone. The outcome was that there should be some better way of doing it... I searched and found this in the code

          % remove this function itself and the ft_xxx calling function
          stack = stack(3:end);
      - +@isprivate: "0"
        commentid: "19609"
        comment_count: "7"
        who:
          +content: r.oostenveld
          +@name: Robert Oostenveld
        bug_when: 2018-11-27 17:23:27 +0100
        thetext: |-
          this has been resolved in https://github.com/fieldtrip/fieldtrip/pull/890

          Please reopen if you are still confused by the error messages.
      - +@isprivate: "0"
        commentid: "20374"
        comment_count: "8"
        who:
          +content: r.oostenveld
          +@name: Robert Oostenveld
        bug_when: 2019-08-10 12:37:17 +0200
        thetext: "This closes a whole series of bugs that have been resolved (either FIXED/WONTFIX/INVALID) for quite some time. \n\nIf you disagree, please file a new issue on https://github.com/fieldtrip/fieldtrip/issues."
