+p_xml: 'version="1.0" encoding="UTF-8" standalone="yes" '
+directive: DOCTYPE bugzilla SYSTEM "http://bugzilla.fieldtriptoolbox.org/page.cgi?id=bugzilla.dtd"
bugzilla:
  +@version: 4.4.1
  +@urlbase: http://bugzilla.fieldtriptoolbox.org/
  +@maintainer: r.oostenveld@donders.ru.nl
  bug:
    bug_id: "512"
    creation_ts: 2011-03-02 11:14:00 +0100
    short_desc: ft_sourceplot can't plot mri
    delta_ts: 2011-03-03 10:04:41 +0100
    reporter_accessible: "1"
    cclist_accessible: "1"
    classification_id: "1"
    classification: Unclassified
    product: FieldTrip
    component: plotting
    version: unspecified
    rep_platform: PC
    op_sys: Linux
    bug_status: CLOSED
    resolution: FIXED
    bug_file_loc:
    status_whiteboard:
    keywords:
    priority: P1
    bug_severity: normal
    target_milestone: '---'
    everconfirmed: "1"
    reporter:
      +content: lilla.magyari
      +@name: Lilla Magyari
    assigned_to:
      +content: j.schoffelen
      +@name: Jan-Mathijs Schoffelen
    cc: j.schoffelen
    comment_sort_order: oldest_to_newest
    long_desc:
      - +@isprivate: "0"
        commentid: "1547"
        comment_count: "0"
        who:
          +content: lilla.magyari
          +@name: Lilla Magyari
        bug_when: 2011-03-02 11:14:39 +0100
        thetext: |-
          hi,

          ft_sourceplot worked last night, but today morning I could not use it anymore.
          I have tried to do this:

          cd /home/coherence/roboos/data/lilmag/subjects/subject01/mri;
          mri = ft_read_mri('filled.mgz');
          cfg = [];
          cfg.interactive = 'yes';
          figure;ft_sourceplot(cfg, mri);

          And I have got this:

          >> ft_sourceplot(cfg, mri);
          the input is volume data with dimensions [256 256 256]
          ??? Undefined function or variable "data".

          Error in ==> ft_datatype_vol at 72
          if isfield(data, 'xgrid'),     data = rmfield(data,
          'xgrid');     end

          Error in ==> ft_checkdata at 169
            data = ft_datatype_vol(data);

          Error in ==> ft_sourceplot at 260
          data = ft_checkdata(data, 'datatype', 'volume',
          'feedback', 'yes');


          thanks for helping out with it.

          Lilla
      - +@isprivate: "0"
        commentid: "1548"
        comment_count: "1"
        who:
          +content: j.schoffelen
          +@name: Jan-Mathijs Schoffelen
        bug_when: 2011-03-02 11:31:47 +0100
        thetext: |-
          This was caused by a typo in ft_datatype_source, it has been fixed and I suspect that it works again.

          JM
