+p_xml: 'version="1.0" encoding="UTF-8" standalone="yes" '
+directive: DOCTYPE bugzilla SYSTEM "http://bugzilla.fieldtriptoolbox.org/page.cgi?id=bugzilla.dtd"
bugzilla:
  +@version: 4.4.1
  +@urlbase: http://bugzilla.fieldtriptoolbox.org/
  +@maintainer: r.oostenveld@donders.ru.nl
  bug:
    bug_id: "546"
    creation_ts: 2011-03-23 10:45:00 +0100
    short_desc: matlab startup error
    delta_ts: 2011-03-31 14:13:54 +0200
    reporter_accessible: "1"
    cclist_accessible: "1"
    classification_id: "1"
    classification: Unclassified
    product: FieldTrip
    component: peer
    version: unspecified
    rep_platform: PC
    op_sys: Linux
    bug_status: CLOSED
    resolution: FIXED
    bug_file_loc:
    status_whiteboard:
    keywords:
    priority: P1
    bug_severity: major
    target_milestone: '---'
    everconfirmed: "1"
    reporter:
      +content: marcel.zwiers
      +@name: Marcel Zwiers
    assigned_to:
      +content: r.oostenveld
      +@name: Robert Oostenveld
    comment_sort_order: oldest_to_newest
    long_desc:
      - +@isprivate: "0"
        commentid: "1678"
        comment_count: "0"
        who:
          +content: marcel.zwiers
          +@name: Marcel Zwiers
        bug_when: 2011-03-23 10:45:12 +0100
        thetext: |-
          I suspect a fix for this error is already in the works, but in any case, I get this error every time I do a peercellfun call:

          an error was detected during the execution of job 2
          Error using ==> peerget at 112
          could not start the matlab engine

          Error in ==> peerget at 112
                  error(err);
      - +@isprivate: "0"
        commentid: "1683"
        comment_count: "1"
        who:
          +content: r.oostenveld
          +@name: Robert Oostenveld
        bug_when: 2011-03-23 13:15:35 +0100
        thetext: "I just checked with a simple\n  peercellfun(@pause, {1}) \non mentat and I did not get the error. So it does not happen every time on peercellfun (for me).\n\nCan you provide more info?"
      - +@isprivate: "0"
        commentid: "1684"
        comment_count: "2"
        who:
          +content: marcel.zwiers
          +@name: Marcel Zwiers
        bug_when: 2011-03-23 13:19:47 +0100
        thetext: |-
          peercellfun(@pause, repmat({1},10,1))
          peer: init
          peerinit: marzwi@mentat270.dccn.nl, id = 3590654126
          peer: spawning announce thread
          peer: spawning discover thread
          peer: spawning expire thread
          peer: spawning tcpserver thread
          submitted 1/10, collected 0/10, busy 1, speedup 0.0
          submitted 3/10, collected 0/10, busy 2, speedup 0.0
          submitted 3/10, collected 0/10, busy 3, speedup 0.0
          submitted 5/10, collected 0/10, busy 4, speedup 0.0
          submitted 6/10, collected 0/10, busy 5, speedup 0.0
          an error was detected during the execution of job 10
          ??? Error using ==> peerget at 112
          could not start the matlab engine

          Error in ==> peerget at 112
                  error(err);

          Error in ==> peercellfun at 304
                [argout, options] = peerget(joblist(i).jobid, 'timeout', inf, 'output', 'cell', 'diary',
                diary, 'StopOnError', StopOnError);
      - +@isprivate: "0"
        commentid: "1685"
        comment_count: "3"
        who:
          +content: r.oostenveld
          +@name: Robert Oostenveld
        bug_when: 2011-03-23 13:32:58 +0100
        thetext: |-
          I was able to reproduce.
          The problem was introduced in the changes due to http://bugzilla.fcdonders.nl/show_bug.cgi?id=541
          I have fixed it in r3202.
      - +@isprivate: "0"
        commentid: "1722"
        comment_count: "4"
        who:
          +content: r.oostenveld
          +@name: Robert Oostenveld
        bug_when: 2011-03-31 14:13:54 +0200
        thetext: changed the status of most recently resolved/fixed bugs into "CLOSED"
